clusterName: "{{ cluster_name }}"
platform: agent
nodePool:
  - name: "{{ cluster_name }}-nodepool"
    replicas: {{ number_of_nodes }}
    labels:
      allowDeletion: false
      minReplicas: "{{ number_of_nodes - 1 }}"
      maxReplicas: "{{ number_of_nodes + 1 }}"
    agentLabelSelector:
      nodeLabelKey: infraenv
      nodeLabelValue: classic-baremetal
    configs:
      - "nm-conf-{{ cluster_name }}"
      - worker-kubeconfig
mcConfig:
  - "nm-conf-{{ cluster_name }}"
  - worker-kubeconfig
idms:
  # RedHat artifact mirrors to private artifacts
  mirrors:
    - source: registry.redhat.io
      mirrors:
        - "{{ private_registry }}/redhat"
    - source: quay.io
      mirrors:
        - "{{ private_registry }}/quay"
    - source: registry.access.redhat.com
      mirrors:
        - "{{ private_registry }}/access-redhat"